import javax.swing.*;
import java.awt.*;

public class SequenceAnimaitonTest {

	/**
	 * @param args
	 */

	int x = 70;
	int y = 70;
	Sequence thisSeq;
	public Sequence[] alignment = new Sequence[4];
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		SequenceAnimaitonTest gui = new SequenceAnimaitonTest();
		gui.go();
	}

	public void go(){
		String raw_sequence =      "MRVTGTRKNC-PQC--C---------IWGI---L---GFWIIM-TC--NG-------N-----GMWVTVYYGVPVWRE-AKTTLFCASDAKGYVKEVHNVWATHACVPTDPSPQELVL-P-NVTENFNMWKNDMVDQMHEDIVSLWDQSLKPCVELTPLCVTLNCTNAAAINT-------------------------------------HKNKTNEMK-N-CSFYIDTAV-R-DKKKKENALFYTLDI--VQIDE---------------------------NDNSS-YR-------------------PIPIHFCAPAGYAILK-CNN-KTFN-GTGPCNNVSTV-QCTHGIRPVVS-TQLLLNGS---LAE---ED---IIIRSENLTNNAK--TIIVHLNES--VEIVCTRPNNNTRKGVR---IGPGQTFYATGD--I-IG-NIRQAYCNISRDKWNRTL-HRVSEKLK--EHFP---------NRTIIF--NQS-AGGD-LEIT-THSFNCMGEFFYCNTSGLFNGTYNKTSSN-------TNSTNSNNTEDTIT-LQCRIKQIINMWQKVGRAIYAPPIAGNITCKSNITGILLTRDGG--------------TNTSTTNETFRPGGGEMR-DNWRSELYKYKVVEINPLGIAPTEAKRRVV------QREKR-AV-GIIG-AL-FLGFLGAAGSTMGAASITLTVQARQLLSGIVQQQNNLLRAIEAQQHMLQLTVWGIKQLQARVLAVERYLRDQQLLGIWGCSGKLICTTNVPWNSSW--------------------S-----NK------TKNEIW-D-N--MTWMQWDREISNYTDTIYKLLVDSQNQQERNEKDLLALDKWNDLWNWFDITKWLWYIKIFIMIVGGLIGLRIIFAVLSIVNRVRQGYSPLSLQTLLPNPRG--PDRHGGIEEEGGEQDRDRYI-RLVSGFLPL-VWDDLRNLCLFSYHRLRDFILIAVRAVELLGRSSLRGLQRGWETLKYLGSLVQYWGLELKKSAINLFDTIAIGVAEGTDRILELIQNLC-RGIRNVPRRIRQGF-EAALQ*";
		String raw_sequence3sub =  "AAATGTRKNC-PQC--C---------IWGI---L---GFWIIM-TC--NG-------N-----GMWVTVYYGVPVWRE-AKTTLFCASDAKGYVKEVHNVWATHACVPTDPSPQELVL-P-NVTENFNMWKNDMVDQMHEDIVSLWDQSLKPCVELTPLCVTLNCTNAAAINT-------------------------------------HKNKTNEMK-N-CSFYIDTAV-R-DKKKKENALFYTLDI--VQIDE---------------------------NDNSS-YR-------------------PIPIHFCAPAGYAILK-CNN-KTFN-GTGPCNNVSTV-QCTHGIRPVVS-TQLLLNGS---LAE---ED---IIIRSENLTNNAK--TIIVHLNES--VEIVCTRPNNNTRKGVR---IGPGQTFYATGD--I-IG-NIRQAYCNISRDKWNRTL-HRVSEKLK--EHFP---------NRTIIF--NQS-AGGD-LEIT-THSFNCMGEFFYCNTSGLFNGTYNKTSSN-------TNSTNSNNTEDTIT-LQCRIKQIINMWQKVGRAIYAPPIAGNITCKSNITGILLTRDGG--------------TNTSTTNETFRPGGGEMR-DNWRSELYKYKVVEINPLGIAPTEAKRRVV------QREKR-AV-GIIG-AL-FLGFLGAAGSTMGAASITLTVQARQLLSGIVQQQNNLLRAIEAQQHMLQLTVWGIKQLQARVLAVERYLRDQQLLGIWGCSGKLICTTNVPWNSSW--------------------S-----NK------TKNEIW-D-N--MTWMQWDREISNYTDTIYKLLVDSQNQQERNEKDLLALDKWNDLWNWFDITKWLWYIKIFIMIVGGLIGLRIIFAVLSIVNRVRQGYSPLSLQTLLPNPRG--PDRHGGIEEEGGEQDRDRYI-RLVSGFLPL-VWDDLRNLCLFSYHRLRDFILIAVRAVELLGRSSLRGLQRGWETLKYLGSLVQYWGLELKKSAINLFDTIAIGVAEGTDRILELIQNLC-RGIRNVPRRIRQGF-EAALQ*";
		String raw_sequence5sub =  "AAATGTRKNC-PQC--C---------IWGI---L---GFWIIM-TC--NG-------N-----GMWQQVYYGVPVWRE-AKTTLFCASDAKGYVKEVHNVWATHACVPTDPSPQELVL-P-NVTENFNMWKNDMVDQMHEDIVSLWDQSLKPCVELTPLCVTLNCTNAAAINT-------------------------------------HKNKTNEMK-N-CSFYIDTAV-R-DKKKKENALFYTLDI--VQIDE---------------------------NDNSS-YR-------------------PIPIHFCAPAGYAILK-CNN-KTFN-GTGPCNNVSTV-QCTHGIRPVVS-TQLLLNGS---LAE---ED---IIIRSENLTNNAK--TIIVHLNES--VEIVCTRPNNNTRKGVR---IGPGQTFYATGD--I-IG-NIRQAYCNISRDKWNRTL-HRVSEKLK--EHFP---------NRTIIF--NQS-AGGD-LEIT-THSFNCMGEFFYCNTSGLFNGTYNKTSSN-------TNSTNSNNTEDTIT-LQCRIKQIINMWQKVGRAIYAPPIAGNITCKSNITGILLTRDGG--------------TNTSTTNETFRPGGGEMR-DNWRSELYKYKVVEINPLGIAPTEAKRRVV------QREKR-AV-GIIG-AL-FLGFLGAAGSTMGAASITLTVQARQLLSGIVQQQNNLLRAIEAQQHMLQLTVWGIKQLQARVLAVERYLRDQQLLGIWGCSGKLICTTNVPWNSSW--------------------S-----NK------TKNEIW-D-N--MTWMQWDREISNYTDTIYKLLVDSQNQQERNEKDLLALDKWNDLWNWFDITKWLWYIKIFIMIVGGLIGLRIIFAVLSIVNRVRQGYSPLSLQTLLPNPRG--PDRHGGIEEEGGEQDRDRYI-RLVSGFLPL-VWDDLRNLCLFSYHRLRDFILIAVRAVELLGRSSLRGLQRGWETLKYLGSLVQYWGLELKKSAINLFDTIAIGVAEGTDRILELIQNLC-RGIRNVPRRIRQGF-EAALQ*";
		String raw_sequence10sub = "AAATGTRKNC-PQC--C---------IWGI---L---GFWIIM-TC--NG-------N----AGMWQQVYYGVPVWRE-AKTTLFCASDQQQQQKEVHNVWATHACVPTDPSPQELVL-P-NVTENFNMWKNDMVDQMHEDIVSLWDQSLKPCVELTPLCVTLNCTNAAAINT-------------------------------------HKNKTNEMK-N-CSFYIDTAV-R-DKKKKENALFYTLDI--VQIDE---------------------------NDNSS-YR-------------------PIPIHFCAPAGYAILK-CNN-KTFN-GTGPCNNVSTV-QCTHGIRPVVS-TQLLLNGS---LAE---ED---IIIRSENLTNNAK--TIIVHLNES--VEIVCTRPNNNTRKGVR---IGPGQTFYATGD--I-IG-NIRQAYCNISRDKWNRTL-HRVSEKLK--EHFP---------NRTIIF--NQS-AGGD-LEIT-THSFNCMGEFFYCNTSGLFNGTYNKTSSN-------TNSTNSNNTEDTIT-LQCRIKQIINMWQKVGRAIYAPPIAGNITCKSNITGILLTRDGG--------------TNTSTTNETFRPGGGEMR-DNWRSELYKYKVVEINPLGIAPTEAKRRVV------QREKR-AV-GIIG-AL-FLGFLGAAGSTMGAASITLTVQARQLLSGIVQQQNNLLRAIEAQQHMLQLTVWGIKQLQARVLAVERYLRDQQLLGIWGCSGKLICTTNVPWNSSW--------------------S-----NK------TKNEIW-D-N--MTWMQWDREISNYTDTIYKLLVDSQNQQERNEKDLLALDKWNDLWNWFDITKWLWYIKIFIMIVGGLIGLRIIFAVLSIVNRVRQGYSPLSLQTLLPNPRG--PDRHGGIEEEGGEQDRDRYI-RLVSGFLPL-VWDDLRNLCLFSYHRLRDFILIAVRAVELLGRSSLRGLQRGWETLKYLGSLVQYWGLELKKSAINLFDTIAIGVAEGTDRILELIQNLC-RGIRNVPRRIRQGF-EAALQ*";

		Sequence s1 = new Sequence( "HXB2",raw_sequence);
		Sequence s2 = new Sequence( "3sub",raw_sequence3sub);
		Sequence s3 = new Sequence( "5sub",raw_sequence5sub);
		Sequence s4 = new Sequence( "10sub",raw_sequence10sub);
		
		alignment[0] = s1;
		alignment[1] = s2;
		alignment[2] = s3;
		alignment[3] = s4;
		
		System.out.println(s1.getCodons()[2]);

		
		for(Sequence aSeq:alignment){
			thisSeq = aSeq;
			thisSeq.determineSubstitutions(raw_sequence);
			thisSeq.determineGaps();
			System.out.println(thisSeq.getName()+" subs "+thisSeq.num_subs+" gaps "+thisSeq.getNum_gaps());
			
		}

	}
}
